#ifndef __INC_LOGHTML_H
#define __INC_LOGHTML_H

const char* loghtml = "<!DOCTYPE html>\n"
"<script>\n"
"let eventSource;\n"
"\n"
"function start() { \n"
"  if (!window.EventSource) {\n"
"    // IE or an old browser\n"
"    alert(\"The browser doesn't support EventSource.\");\n"
"    return;\n"
"  }\n"
"\n"
"  eventSource = new EventSource('logevent');\n"
"\n"
"  eventSource.onopen = function(e) {\n"
"    console.log(\"Event: open\");\n"
"  };\n"
"\n"
"  eventSource.onerror = function(e) {\n"
"    console.log(\"Event: error\");\n"
"    if (this.readyState == EventSource.CONNECTING) {\n"
"      console.log(`Reconnecting (readyState=${this.readyState})...`);\n"
"    } else {\n"
"      console.log(\"Error has occured.\");\n"
"    }\n"
"  };\n"
"\n"
"  eventSource.addEventListener('bye', function(e) {\n"
"    log(e.data);\n"
"  });\n"
"\n"
"  eventSource.onmessage = function(e) {\n"
"    log(e.data);\n"
"  };\n"
"}\n"
"\n"
"function stop() {\n"
"  eventSource.close();\n"
"  console.log(\"eventSource.close()\");\n"
"}\n"
"\n"
"function log(msg) {\n"
"  logElem.innerHTML += msg + \"<br>\";\n"
"  document.documentElement.scrollTop = 99999999;\n"
"}\n"
"</script>\n"
"\n"
"<body onLoad=\"start()\" onUnload=\"stop()\">\n"
"<div id=\"logElem\" style=\"margin: 6px 0\"></div>\n"
"</body>\n";
#endif